# This rule is not used by the project pod-rightsizer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over optimization.pod-rightsizer.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-rightsizer
    app.kubernetes.io/managed-by: kustomize
  name: podrightsizerecommendation-admin-role
rules:
- apiGroups:
  - optimization.pod-rightsizer.com
  resources:
  - podrightsizerecommendations
  verbs:
  - '*'
- apiGroups:
  - optimization.pod-rightsizer.com
  resources:
  - podrightsizerecommendations/status
  verbs:
  - get
